//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ImportExcelDBEntities : DbContext
    {
        public ImportExcelDBEntities()
            : base("name=ImportExcelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblProject> tblProjects { get; set; }
        public virtual DbSet<tblRoleMaster> tblRoleMasters { get; set; }
        public virtual DbSet<tblTGBuxar> tblTGBuxars { get; set; }
    
        public virtual ObjectResult<GetProjectItemCount_Result> GetProjectItemCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectItemCount_Result>("GetProjectItemCount");
        }
    }
}
