//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTGBuxar
    {
        public int ID { get; set; }
        public string DrawingNo { get; set; }
        public string MarkNo { get; set; }
        public string Batch { get; set; }
        public string PartSerialNo { get; set; }
        public string UnitWT { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedBy { get; set; }
    }
}
